first_app/urls.py
from django.urls import path
from . import views

app_name = 'first_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>', views.SchoolDetailView.as_view(), name='school-detail'),
    path('create', views.SchoolCreateView.as_view(), name='create'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(), name='delete'),
    path('update/<int:pk>', views.SchoolUpdateView.as_view(), name='update'),
]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls', namespace='first_app'))
]

first_app/models.py
from django.db import models
from django.urls import reverse

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # after creation is complete go back to this link with these args
        return reverse('first_app:school-detail', kwargs={'pk': self.pk})


class Student(models.Model):
        name = models.CharField(max_length=256)
        age = models.PositiveIntegerField()
        school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

        def __str__(self):
            return self.name

first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_app/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView,ListView,DeleteView,
                                DetailView,CreateView,UpdateView)
from django.urls import reverse_lazy
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    model = models.School

    # changes school_list to schools
    context_object_name = 'schools'

class SchoolDetailView(DetailView):
    model = models.School
    template_name = 'first_app/school_detail.html'

    # changes school to school_detail
    context_object_name = 'school_detail'

class SchoolCreateView(CreateView):
    model = models.School
    fields = ('name', 'principal', 'location')

class SchoolUpdateView(UpdateView):
    model = models.School
    fields = ('name', 'principal')

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('first_app:list')

first_app/templates/first_app/first_app_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <title>Base</title>
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li>
                <a href="{% url 'first_app:list' %}" class="navbar-brand">Schools</a>
            </li>
            <li>
                <a href="{% url 'admin:index' %}" class="navbar-link">Admin</a>
            </li>
            <li>
                <a href="#" class="navbar-link"></a>
            </li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>

</html>

first_app/templates/first_app/school_confirm_delete.html
{% extends 'first_app/first_app_base.html' %}
{% block body_block %}

<h1>Delete {{school}} ?</h1>
<form method='post'>
    {% csrf_token %}
    <input type="submit" class='btn btn-danger' value ='Delete'>
    <a href="{% url 'first_app:school-detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

first_app/templates/first_app/school_detail.html
{% extends 'first_app/first_app_base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to the school detail page</h1>
    <h2>
        School details:
    </h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>
    <h3>Students:</h3>

    {% for student in school_detail.students.all %}
    <p>{{student}} who is {{student.age}} years old</p>
    {% endfor %}
</div>

<div class="container">
    <p><a class='btn btn-warning' href="{% url 'first_app:update' pk=school_detail.pk %}">Update</a></p>
</div>

{% endblock %}

first_app/templates/first_app/school_form.html
{% extends 'first_app/first_app_base.html' %}
{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form method='post'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class='btn btn-primary' value='Submit'>
</form>

{% endblock %}

first_app/templates/first_app/school_list.html
{% extends 'first_app/first_app_base.html' %}

{% block body_block %}

<h1>Welcome to a list of all the schools!</h1>

<ol>
    {% for school in schools %}
    <h2>
        <li><a href="{{school.id}}">
                {{school.name}}

        </a>
        </li>
    </h2>
    {% endfor %}
</ol>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <title>Base</title>
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li>
                <a href="{% url 'first_app:list' %}" class="navbar-brand">Schools</a>
            </li>
            <li>
                <a href="{% url 'admin:index' %}" class="navbar-link">Admin</a>
            </li>
            <li>
                <a href="#" class="navbar-link"></a>
            </li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>

</html>

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Document</title>
</head>

<body>
    <nav>
        <div class="container">
            <ul class="nav">
                <li class='nav-item'>
                    <a href="{% url 'index' %}" class="nav-link">DJANGO</a>
                </li>
                <li class='nav-item'>
                    <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
                </li>
                <li class='nav-item'>
                    <a href="{% url 'first_app:register' %}" class="nav-link">Register</a>
                </li>

                {% if user.is_authenticated %}
                <li class='nav-item'>
                    <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                </li>
                <li class='nav-item'>
                        <a href="{% url 'special' %}" class="nav-link">Special</a>
                    </li>
                {% else %}
                <li class='nav-item'>
                    <a href="{% url 'first_app:user_login' %}" class="nav-link">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </nav>

</body>

</html>

templates/first_app/forms.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Forms</title>
</head>

<body>
    <h1>
        Fill out the form!
    </h1>
    <div class="container">
        <form action="" method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class='btn btn-primary' value='Submit'>
        </form>

    </div>
</body>

</html>

templates/first_app/login.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>

    <form action="{% url 'first_app:user_login' %}" method='post'>
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name='username' placeholder='Enter Username'>

        <label for="password">Password: </label>
        <input type="password" name='password' >

        <input type="submit" name='' value='Login'>
    </form>
</div>

{% endblock %}

templates/first_app/other.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% load my_custom_template %}

{% block body_block %}
<h1>Welcome to other</h1>
<h2>This is an example of template inheritance</h2>
<h3>
    {{text | bailey_cut:'he'}}
</h3>
<h3>
    {{number | add:'99'}}
</h3>
{% endblock %}

templates/first_app/registration.html
{% extends 'first_app/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>THANK YOU FOR REGISTERING</h1>

    {% else %}
    <h1>
        Register Here
    </h1>
    <h3>Fill out the form:</h3>

    <form method='post' enctype='multipart/form-data'>
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" value='Register'>
    </form>
    {% endif %}
</div>

{% endblock %}

templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to url templates</h1>
    <a href="{% url 'first_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">THE ADMIN PAGE</a>
    <a href="{% url 'index' %}">GO HOME</a>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Home Page</h1>
</div>
{% endblock %}